# Generated by Django 2.2.7 on 2020-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicio_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Apellidos',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
